# Generated by Django 4.2 on 2023-11-07 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'валюту', 'verbose_name_plural': 'Валюта'},
        ),
        migrations.AlterModelOptions(
            name='currencyexchangerates',
            options={'verbose_name': 'курс валюты', 'verbose_name_plural': 'Курсы валюты'},
        ),
        migrations.AlterField(
            model_name='currencyexchangerates',
            name='course',
            field=models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Курс валюты'),
        ),
        migrations.AlterField(
            model_name='currencyexchangerates',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency', verbose_name='Валюта'),
        ),
    ]
