# Generated by Django 4.2 on 2023-07-20 16:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counterparty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counterparty',
            options={'ordering': ['id'], 'verbose_name': 'контрагент', 'verbose_name_plural': 'Контрагенты'},
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='currency',
            field=models.CharField(default=datetime.date(2023, 7, 20), max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counterparty.accounttype', verbose_name='Вид счета'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_name',
            field=models.CharField(max_length=128, verbose_name='Наименование банка'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='bik',
            field=models.CharField(max_length=9, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='checking_account',
            field=models.CharField(max_length=20, verbose_name='Расчетный счет'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='correspondent_account',
            field=models.CharField(max_length=20, verbose_name='Корр. Счет'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='current',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counterparty.currency', verbose_name='Валюта счета'),
        ),
        migrations.CreateModel(
            name='SignatoryContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_i', models.CharField(max_length=128, verbose_name='ФИО в именительном падеже')),
                ('fio_r', models.CharField(max_length=128, verbose_name='ФИО в родительном падеже')),
                ('post_i', models.CharField(max_length=128, verbose_name='Должность в именительном падеже')),
                ('post_r', models.CharField(max_length=128, verbose_name='Должность в родительном падеже')),
                ('document', models.CharField(max_length=128, verbose_name='Документ - основание в родительном падеже')),
                ('counterparty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='counterparty.counterparty')),
            ],
        ),
    ]
