# Generated by Django 4.2 on 2023-07-20 17:19

from django.db import migrations, models
import django.db.models.deletion

def fill_category(apps, schema_editor):
    BankDetails = apps.get_model('counterparty', 'BankDetails')
    
    for b in BankDetails.objects.all():
        b.currency_id = b.currencybak_id
        b.save()


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
        ('counterparty', '0003_auto_20230720_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name="BankDetails",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="currency.Currency",
            ),
        ),
        migrations.RunPython(fill_category),
        migrations.RemoveField('BankDetails', 'currencybak'),
        migrations.DeleteModel("CurrencyBak"),
    ]
