# Generated by Django 4.2 on 2023-11-07 16:27

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_currency_options_and_more'),
        ('counterparty', '0004_auto_20230721_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=128, verbose_name='ФИО')),
                ('post', models.CharField(max_length=128, verbose_name='Должность')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
        ),
        migrations.AddField(
            model_name='signatorycontract',
            name='address_factual',
            field=models.CharField(default=0, max_length=128, verbose_name='Фактический адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signatorycontract',
            name='address_legal',
            field=models.CharField(default=0, max_length=128, verbose_name='Юридический адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signatorycontract',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.currency', verbose_name='Валюта счета'),
        ),
    ]
